"""migration

Revision ID: 1191348db20c
Revises: 7de4a98c7163
Create Date: 2025-03-02 16:01:52.717921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1191348db20c'
down_revision: Union[str, None] = '7de4a98c7163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_imported', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('is_manual', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('is_linked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_linked')
    op.drop_column('transactions', 'is_manual')
    op.drop_column('transactions', 'is_imported')
    # ### end Alembic commands ###
