"""migration

Revision ID: 6b95167a8006
Revises: cd89003d0e9b
Create Date: 2025-03-02 18:53:45.277351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b95167a8006'
down_revision: Union[str, None] = 'cd89003d0e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('original_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['original_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_corrections_category_id'), 'category_corrections', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_corrections_description'), 'category_corrections', ['description'], unique=False)
    op.create_index(op.f('ix_category_corrections_id'), 'category_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_category_corrections_original_category_id'), 'category_corrections', ['original_category_id'], unique=False)
    op.create_index(op.f('ix_category_corrections_user_id'), 'category_corrections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_corrections_user_id'), table_name='category_corrections')
    op.drop_index(op.f('ix_category_corrections_original_category_id'), table_name='category_corrections')
    op.drop_index(op.f('ix_category_corrections_id'), table_name='category_corrections')
    op.drop_index(op.f('ix_category_corrections_description'), table_name='category_corrections')
    op.drop_index(op.f('ix_category_corrections_category_id'), table_name='category_corrections')
    op.drop_table('category_corrections')
    # ### end Alembic commands ###
