"""migration

Revision ID: 962faecb63c0
Revises: 6b95167a8006
Create Date: 2025-03-02 19:00:45.210428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962faecb63c0'
down_revision: Union[str, None] = '6b95167a8006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_corrections', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.add_column('category_corrections', sa.Column('old_category_id', sa.Integer(), nullable=True))
    op.add_column('category_corrections', sa.Column('new_category_id', sa.Integer(), nullable=True))
    op.drop_index('ix_category_corrections_category_id', table_name='category_corrections')
    op.drop_index('ix_category_corrections_description', table_name='category_corrections')
    op.drop_index('ix_category_corrections_original_category_id', table_name='category_corrections')
    op.create_index(op.f('ix_category_corrections_new_category_id'), 'category_corrections', ['new_category_id'], unique=False)
    op.create_index(op.f('ix_category_corrections_old_category_id'), 'category_corrections', ['old_category_id'], unique=False)
    op.create_index(op.f('ix_category_corrections_transaction_id'), 'category_corrections', ['transaction_id'], unique=False)
    op.drop_constraint('category_corrections_original_category_id_fkey', 'category_corrections', type_='foreignkey')
    op.drop_constraint('category_corrections_category_id_fkey', 'category_corrections', type_='foreignkey')
    op.create_foreign_key(None, 'category_corrections', 'categories', ['new_category_id'], ['id'])
    op.create_foreign_key(None, 'category_corrections', 'categories', ['old_category_id'], ['id'])
    op.create_foreign_key(None, 'category_corrections', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('category_corrections', 'original_category_id')
    op.drop_column('category_corrections', 'category_id')
    op.drop_column('category_corrections', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_corrections', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('category_corrections', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('category_corrections', sa.Column('original_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category_corrections', type_='foreignkey')
    op.drop_constraint(None, 'category_corrections', type_='foreignkey')
    op.drop_constraint(None, 'category_corrections', type_='foreignkey')
    op.create_foreign_key('category_corrections_category_id_fkey', 'category_corrections', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('category_corrections_original_category_id_fkey', 'category_corrections', 'categories', ['original_category_id'], ['id'])
    op.drop_index(op.f('ix_category_corrections_transaction_id'), table_name='category_corrections')
    op.drop_index(op.f('ix_category_corrections_old_category_id'), table_name='category_corrections')
    op.drop_index(op.f('ix_category_corrections_new_category_id'), table_name='category_corrections')
    op.create_index('ix_category_corrections_original_category_id', 'category_corrections', ['original_category_id'], unique=False)
    op.create_index('ix_category_corrections_description', 'category_corrections', ['description'], unique=False)
    op.create_index('ix_category_corrections_category_id', 'category_corrections', ['category_id'], unique=False)
    op.drop_column('category_corrections', 'new_category_id')
    op.drop_column('category_corrections', 'old_category_id')
    op.drop_column('category_corrections', 'transaction_id')
    # ### end Alembic commands ###
