"""migration

Revision ID: cd89003d0e9b
Revises: 1191348db20c
Create Date: 2025-03-02 16:05:25.542327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd89003d0e9b'
down_revision: Union[str, None] = '1191348db20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_imported', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('is_manual', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('is_linked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_linked')
    op.drop_column('transactions', 'is_manual')
    op.drop_column('transactions', 'is_imported')
    # ### end Alembic commands ###
